name: Compile WASM

on:
  push:
    branches:
      - master

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go version
      - run: make test
      - run: make build
      - name: Push commit to branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'martti@marttilaine.com'
          rm .gitignore
          git update-index --refresh
          git diff-index --quiet HEAD -- || {
            echo "There were changes. Committing.";
            git add dist/*;
            git commit -m "[GitHub action] WASM module";
            git push
          }
